tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: echo "Helloe"
    init: cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    # command: |
    #   cd /workspace
    #   sudo ./aws/install
    #   cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - 42Crunch.vscode-openapi